title: "Julia Kukulies"
author: "Julia Kukulies"
description: "University of Gothenburg"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"


# Layout
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header


# Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "about_me.html", title: "About Me"}
  - {file: "research_interests.md", title: "Research interests"}
  - {file: "resume.html", title: "CV"}
  - {file: "publication_list.html", title: "Publications"}
  - {file: "teaching.html", title: "Teaching"}
  - {file: "extra.html", title: "Experience"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:julia.kukulies@gu.se"}
  - {title: Github, icon: github, url: "https://github.com/JuliaKukulies/juliakukulies.github.io"}
  # - {title: ResearchGate, url: "https://www.researchgate.net/profile/Julia-Kukulies-2"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
